### PR TITLE
U forgot a "t"

### PR DESCRIPTION
**Pull request by cheyao**
Ye i don't know python but i know kotlin so u can trust me

### CODE REVIEW

**Review by Omicron166 — CHANGES_REQUESTED** [review]
true, but you forget about `if defaulconf:` on line 68

**Comment by cheyao** [comment]
> true, but you forget about `if defaulconf:` on line 68

thx added it now, just need to wait till the branch gets merged

**Comment by cheyao** [comment]
@mohinparamasivam merge this pls

**Review by Omicron166 — APPROVED** [review]
Now everything works fine

**Pull request merged**
